### ISSUE TITLE
Sample application: retreiving secrets with an init container

### ISSUE THREAD

**Issue by butler54** [validatedpatterns/coco-pattern#21]
Use a simple application to demostrate that secrets can be retrieved using an init container and stored on disk. This makes retrieving secrets from the CDH have a similar behaviour to volume-mounting standard kubernetes secrets.

**Comment by butler54** [comment]
This is mostly complete with kbs-access. However, today it violates the self contained nature of the pattern.

**Comment by butler54** [comment]
This appears to already be implemented — `charts/coco-supported/kbs-access-curl` demonstrates exactly this pattern:

```yaml
# charts/coco-supported/kbs-access-curl/templates/deployment.yaml
initContainers:
  - name: curl
    image: {{ .Values.initImage }}
    command: ['sh', '-c', 'curl -s http://127.0.0.1:8006/cdh/resource/default/kbsres1/key3 > /var/www/html/secret.txt']
```

An init container calls the local CDH API to fetch a KBS-served secret and writes it to a shared `emptyDir` volume, which the main `httpd` container then serves — i.e. secret retrieval via init container, stored on disk, analogous to a standard Kubernetes Secret volume mount. This chart's own README describes it as demonstrating exactly this.

Suggest closing as resolved, unless there was a more specific scenario in mind (e.g. writing to a real block/file volume rather than emptyDir) that this doesn't cover.
